### ISSUE TITLE
Regression - pyftdi package dependency fails

### ISSUE THREAD

**Issue by aseemjakhar** [eblot/pyi2cflash#1]
Hi,

I use py2cflash and pyspiflash for my project https://gitlab.com/expliot_framework/expliot
The installation is breaking now. I checked both pyi2cflash and pyspiflash. pyftdi version in setup.py INSTALL_REQUIRES recently changed and seems to be causing pyftdi installation failure. Tried in a fresh installation (new machine/first install). Can you please let me know if its something else?

Pipeline failure link here for gitlab jobs - https://gitlab.com/expliot_framework/expliot/-/jobs/361227107

Local machine Error here - 
Error:
Installed /usr/local/lib/python3.7/dist-packages/expliot-0.6.0-py3.7.egg
Processing dependencies for expliot==0.6.0
Searching for pyftdi<0.50,>=0.42
Reading https://pypi.org/simple/pyftdi/
No local packages or working download links found for pyftdi<0.50,>=0.42
error: Could not find suitable distribution for Requirement.parse('pyftdi<0.50,>=0.42')

Kali OS details:
root@kali:~/workspace_expliot/expliot# uname -a
Linux kali 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

root@kali: ~/workspace_expliot/expliot# uname -srm
Linux 4.19.0-kali4-amd64 x86_64

root@kali: ~/workspace_expliot/expliot# lsb_release -a
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.4
Codename:	kali-rolling
root@kali: ~/workspace_expliot/expliot# lsb_release -d
Description:	Kali GNU/Linux Rolling

root@kali: ~/workspace_expliot/expliot# cat /etc/os-release
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.4"
VERSION_ID="2019.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Comment by eblot** [comment]
Sorry, I made an error uploading 0.42.0 to PyPi.org (invalid file name) and there is no way back on PyPi. It is impossible to fix an error but to upload a new version, even if the content is identical.

I've just uploaded a new version (0.42.2) along with a documentation update, so it should now work:

    $ python3 -m venv ~/Python/I2cFlash
    
    $ . ~/Python/I2cFlash/bin/activate
    (I2cFlash) eblot@spey:~
    
    $ pip3 install pyi2cflash
    Collecting pyi2cflash
      Using cached https://files.pythonhosted.org/packages/02/1c/    f3341501185853f09c2f111f4404a6b0d369e72fbd4aa05efb59f2757d01/pyi2cflash-0.2.1.tar.gz
    Collecting pyftdi<0.50,>=0.42 (from pyi2cflash)
      Downloading https://files.pythonhosted.org/packages/    e9/9f/6cecb794fd5a4f9f4026815e3138960aa8814634f2fa642a4c2eba980b46/pyftdi-0.42.2.tar.gz (86kB)
         |████████████████████████████████| 92kB 2.6MB/s
    Collecting pyusb>=1.0.0 (from pyftdi<0.50,>=0.42->pyi2cflash)
    Collecting pyserial>=3.0 (from pyftdi<0.50,>=0.42->pyi2cflash)
      Using cached https://files.pythonhosted.org/packages/0d/    e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl
    Installing collected packages: pyusb, pyserial, pyftdi, pyi2cflash
      Running setup.py install for pyftdi ... done
      Running setup.py install for pyi2cflash ... done
    Successfully installed pyftdi-0.42.2 pyi2cflash-0.2.1 pyserial-3.4 pyusb-1.0.2
