### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fabaff** [eblot/pyi2cflash#2]
The pinning of pyftdi is currently blocking the installation of `pyi2cflash` in Fedora as we already ship `pyftdi-0.51.0`. This was fixed in https://github.com/eblot/pyi2cflash/tree/d5af6795df15a0619a802fe0bc033942a3be713e.

Could you please publish a new release? Thanks.

**Comment by eblot** [comment]
I have not get a chance to validate it with the latest pyftdi version - hence the hold.
Did you give it a try?

**Comment by eblot** [comment]
v0.2.2 should address this issue.

**Comment by fabaff** [comment]
Thanks. Updates are on the way.
